Shamir final
medispring/icc-api pull request #188
Opened 2020-06-03 16:46 UTC by phil1618

2020-09-28 10:02 UTC, sebastienB12 commented on icc-x-api/icc-crypto-x-api.ts
> +          hcp.hcPartyKeys![hcp.parentId!][1],
notaries[0] instead of parentId

2020-09-29 10:58 UTC, sebastienB12 approved these changes

2020-09-29 12:08 UTC, gpiroux requested changes

2020-09-29 12:08 UTC, gpiroux commented on icc-x-api/icc-crypto-x-api.ts
> +  ): Promise<void> {
The name of the method should be more explicit regarding it purpose which is very specific.

2020-09-29 12:08 UTC, gpiroux commented on icc-x-api/icc-crypto-x-api.ts
> +          Promise.resolve([] as string[])
Not required regarding the specific feature

2020-10-19 08:37 UTC, merged